apiVersion: v1
kind: Secret
metadata:
  name: docker-auth
  namespace: admin
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJuaWtzaGF2IiwicGFzc3dvcmQiOiJkY2tyX3BhdF94V0k0RHBvU3BWTlVEQTBnd0RRMDA2TG9zWVUifX19"